In [1]:
class Range(object):
    def __init__(self, start=0, end=10):
        self.counter = start
        self.end = end

    def next(self):
        if self.counter < self.end:
            res = self.counter
            self.counter += 1
            return res
        else:
            return None # optional

In [2]:
class Reverse(object):
    """Iterator for looping over a sequence backwards."""
    def __init__(self, data):
        self.data = data
        self.index = len(data)

    def __iter__(self):
        return self

    def next(self):
        if self.index == 0:
            raise StopIteration
        self.index = self.index - 1
        print(f'index is {self.index} ')
        return self.data[self.index]

In [3]:
rev = Reverse([1,2,3,4])
rev.next()
# for x in rev.next():
#     print (x)

index is 3 


4

In [4]:
a= 5-2+1
b=5-(2+1)
a, b

(4, 2)

In [5]:
import numpy as np

In [6]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [7]:
print(sum(range(5),-1))

9


In [8]:
Z=range(5)

In [9]:
X = np.ones((10,12))
#X = 3.5
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
def generate(X):
    for x in X:
        #print(x)
        yield x

In [11]:
#Z = np.fromiter(generate(X),dtype=float)
#print(Z)

In [12]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z['y'], Z.shape)

[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]] (5, 5)


In [13]:
v = np.random.uniform(0,100,10)
v

array([43.61371115, 59.67642833, 32.99882151, 59.7796349 , 12.98076596,
       57.75414475, 19.89150353, 36.1136151 , 17.38320994, 22.05380491])

In [14]:
Z = np.random.random((10,2,3))
Z

array([[[0.59203406, 0.02321212, 0.24406972],
        [0.15448441, 0.30815937, 0.31830695]],

       [[0.60630996, 0.9749189 , 0.63082174],
        [0.68953791, 0.50794606, 0.05016541]],

       [[0.75614156, 0.6345414 , 0.65271192],
        [0.12543264, 0.98759285, 0.64028191]],

       [[0.19718829, 0.4469551 , 0.17507209],
        [0.64099656, 0.69861312, 0.31553058]],

       [[0.58572665, 0.88458738, 0.19054044],
        [0.63561133, 0.7312212 , 0.59991536]],

       [[0.62983121, 0.26982091, 0.06826939],
        [0.04267944, 0.63773289, 0.32257   ]],

       [[0.78986821, 0.87993953, 0.61434521],
        [0.05407479, 0.49319139, 0.58763804]],

       [[0.67958911, 0.6089531 , 0.86478829],
        [0.39409913, 0.56058538, 0.87037467]],

       [[0.73484874, 0.70726105, 0.37551305],
        [0.65525539, 0.5618065 , 0.85994431]],

       [[0.34941864, 0.54408102, 0.20606095],
        [0.20534081, 0.04182631, 0.00285412]]])

In [15]:
A = np.arange(3).reshape(3,1)
B =np.arange(3)
A, B.shape

(array([[0],
        [1],
        [2]]),
 (3,))

In [16]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [17]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(10)
print(Z, 'Z \n')
print(sliding_window_view(Z, window_shape=3).sum(axis=-1))

[0 1 2 3 4 5 6 7 8 9] Z 

[ 3  6  9 12 15 18 21 24]


## Recursion.  
- self referential.  
- **A data structure is recursive if it can be defined in terms of a smaller version of itself. A list is an example of a recursive data structure.** 

In [18]:
houses = ["Eric's house", "Kenny's house", "Kyle's house", "Stan's house"]

In [19]:


# Each function call represents an elf doing his work 
def deliver_presents_recursively(houses):
    # Worker elf doing his work
    counter = 0

    if len(houses) == 1:
        house = houses[0]
        print("Delivering presents to", house)
        counter+=1
        print(f'counter {counter} 1')

    # Manager elf doing his work
    else:
        mid = len(houses) // 2
        first_half = houses[:mid]
        print(f'first half {first_half}')
        counter+=1
        print(f'counter {counter} 2')        
        second_half = houses[mid:]
        print(f'2nd half {second_half}')
        # Divides his work among two elves
        deliver_presents_recursively(first_half)
        print(f'counter {counter} 3')
        deliver_presents_recursively(second_half)

In [20]:
deliver_presents_recursively(houses)

first half ["Eric's house", "Kenny's house"]
counter 1 2
2nd half ["Kyle's house", "Stan's house"]
first half ["Eric's house"]
counter 1 2
2nd half ["Kenny's house"]
Delivering presents to Eric's house
counter 1 1
counter 1 3
Delivering presents to Kenny's house
counter 1 1
counter 1 3
first half ["Kyle's house"]
counter 1 2
2nd half ["Stan's house"]
Delivering presents to Kyle's house
counter 1 1
counter 1 3
Delivering presents to Stan's house
counter 1 1


In [21]:
def sum_recursive(current_number, accumulated_sum):
    # Base case
    # Return the final state
    if current_number == 11:
        return accumulated_sum

    # Recursive case
    # Thread the state through the recursive call
    else:
       
        final = sum_recursive(current_number + 1, accumulated_sum + current_number)
        print(f'current and accum {current_number, accumulated_sum}')
        return final

In [22]:
sum_recursive(1, 0)

current and accum (10, 45)
current and accum (9, 36)
current and accum (8, 28)
current and accum (7, 21)
current and accum (6, 15)
current and accum (5, 10)
current and accum (4, 6)
current and accum (3, 3)
current and accum (2, 1)
current and accum (1, 0)


55

In [23]:
a = list(range(5))
b = [2,3]
d= ['hello']
a, b, d

([0, 1, 2, 3, 4], [2, 3], ['hello'])

In [24]:
a+b+d

[0, 1, 2, 3, 4, 2, 3, 'hello']

In [25]:
a=[b[0]] + b[1:]
a

[2, 3]

In [26]:
def list_sum_recursive(input_list):
    counter=0
    # Base case
    if input_list == []:
        print(f'empty {input_list}')
        return 0

    # Recursive case
    # Decompose the original problem into simpler instances of the same problem
    # by making use of the fact that the input is a recursive data structure
    # and can be defined in terms of a smaller version of itself
    
    else:
        counter +=1
        head = input_list[0]
        smaller_list = input_list[1:]
        print(f'head {head} and smaller {smaller_list}, counter is {counter}')
        final = head + list_sum_recursive(smaller_list)
        print(f'final {final},  counter is {counter}')
        return final

In [27]:
list_sum_recursive([1, 2, 3])

head 1 and smaller [2, 3], counter is 1
head 2 and smaller [3], counter is 1
head 3 and smaller [], counter is 1
empty []
final 3,  counter is 1
final 5,  counter is 1
final 6,  counter is 1


6

In [28]:
import numpy as np
A = np.matrix([[4,3,10], [2,1,7], [3,2,8],[12,2,3]])
B = np.matrix([[1,2,1,3,1], [3,4,7,2,10],[2,10,1,2,3]])


In [29]:
#Dot product/matrix multiplication using einsum
C = np.einsum('il,lj->ij', A,B)
C

array([[ 33, 120,  35,  38,  64],
       [ 19,  78,  16,  22,  33],
       [ 25,  94,  25,  29,  47],
       [ 24,  62,  29,  46,  41]])

In [30]:
E = np.arange(12).reshape(np.shape(A))
E1 = np.matrix(E)
E1

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [31]:
np.shape(A), np.shape(E1)

((4, 3), (4, 3))

In [32]:
#Element-wise Multiplication
D=np.einsum('ij,ij->ij', A,E1)
D

array([[  0,   3,  20],
       [  6,   4,  35],
       [ 18,  14,  64],
       [108,  20,  33]])

In [33]:
np.multiply(A,E)

matrix([[  0,   3,  20],
        [  6,   4,  35],
        [ 18,  14,  64],
        [108,  20,  33]])

In [34]:
#SUM of A
D=np.einsum('ij->', A)
D

57

UsageError: Cell magic `%%sql` not found.
